---
http_interactions:
- request:
    method: get
    uri: http://localhost:3000/products.json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      User-Agent:
      - Ruby
      X-Api-Key:
      - 4d26276a99cf2b1291000001
      X-Api-Timestamp:
      - '1331661732'
      X-Api-Signature:
      - !binary |-
        ZjI3OGE5MjJlMmMwNjFjZjE5NzM2NDk2NmU4YjgxM2Y=
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 13 Mar 2012 18:02:12 GMT
      Status:
      - 200 OK
      Connection:
      - close
      X-Csrf-Token:
      - LEQv5es+zCAFbzNJaXsYQeBSoVpKtxAU9oix4m+dVVw=
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge
      Etag:
      - ! '"95cd452ca7f3a19d92bf9a816fcf2b19"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      Set-Cookie:
      - _hippo_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFRkkiJTk0NDNkNDQ1NDYwMGUxMWZkNzBhNGFkYzFiODhiYjBiBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMUxFUXY1ZXMrekNBRmJ6TkphWHNZUWVCU29WcEt0eEFVOW9peDRtK2RWVnc9BjsARg%3D%3D--ed69346bf7d92ee41e65288e88d79bfc5a7034ef;
        path=/; HttpOnly
      X-Request-Id:
      - bbc5fd8d475a29ac5e9535d96bdb8c87
      X-Runtime:
      - '0.056341'
    body:
      encoding: US-ASCII
      string: ! '[{"id":"4d76a704f7764853be000001","courses":[{"id":"4d76a706f7764853be000003","changelog":null,"created_at":null,"mapleta_parent_id":5,"name":"Calculus","theme":"","user_roles":[],"product_id":"4d76a704f7764853be000001"}],"created_at":"2011-03-07T18:00:00-06:00","default_course_id":"4d76a706f7764853be000003","name":"Calculus
        Test","updated_at":"2012-03-13T11:51:58-05:00","user_roles":[]},{"id":"4dee712af776482745000001","courses":[{"id":"4dee712bf776482745000003","changelog":null,"created_at":"2011-06-06T19:00:00-05:00","mapleta_parent_id":6,"name":"College
        Algebra","theme":null,"user_roles":[],"product_id":"4dee712af776482745000001"},{"id":"4ea712787fd4eff455000002","changelog":null,"created_at":"2011-10-24T19:00:00-05:00","mapleta_parent_id":6,"name":"College
        Algebra 2nd Edition","theme":null,"user_roles":[],"product_id":"4dee712af776482745000001"}],"created_at":"2011-06-06T19:00:00-05:00","default_course_id":"4dee712bf776482745000003","name":"College
        Algebra","updated_at":"2011-11-23T12:05:37-06:00","user_roles":[]}]'
    http_version: 
  recorded_at: Tue, 13 Mar 2012 18:02:12 GMT
recorded_with: VCR 2.0.0
