---
http_interactions:
- request:
    method: get
    uri: http://localhost:3000/products/4d76a704f7764853be000001.json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      User-Agent:
      - Ruby
      X-Api-Key:
      - 4d26276a99cf2b1291000001
      X-Api-Timestamp:
      - '1331661732'
      X-Api-Signature:
      - !binary |-
        OThjYzI5NTcyMDJiZjZlYTI5OTZkNzU3NDA4ODEyOWM=
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 13 Mar 2012 18:02:12 GMT
      Status:
      - 200 OK
      Connection:
      - close
      X-Csrf-Token:
      - k+FIgIu/lCn8Rd5Nld43JT/BXOmBrl7nBe/8MUvRoJ4=
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge
      Etag:
      - ! '"4e53a3703c9096cb34bb8e9c6084e751"'
      Cache-Control:
      - max-age=0, private, must-revalidate
      Set-Cookie:
      - _hippo_session=BAh7B0kiD3Nlc3Npb25faWQGOgZFRkkiJWI4MjVlNDBiMmE2NjdiOWJjNTkxY2Y5NDVhMzY3NGU3BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMWsrRklnSXUvbENuOFJkNU5sZDQzSlQvQlhPbUJybDduQmUvOE1VdlJvSjQ9BjsARg%3D%3D--93d21bbc433504ec04ecb2f972c23d48ae2655a5;
        path=/; HttpOnly
      X-Request-Id:
      - ab51ed0cd7982474c7fa474ead01592f
      X-Runtime:
      - '0.011356'
    body:
      encoding: US-ASCII
      string: ! '{"id":"4d76a704f7764853be000001","courses":[{"id":"4d76a706f7764853be000003","changelog":null,"created_at":null,"mapleta_parent_id":5,"name":"Calculus","theme":"","user_roles":[],"product_id":"4d76a704f7764853be000001"}],"created_at":"2011-03-07T18:00:00-06:00","default_course_id":"4d76a706f7764853be000003","name":"Calculus
        Test","updated_at":"2012-03-13T11:51:58-05:00","user_roles":[]}'
    http_version: 
  recorded_at: Tue, 13 Mar 2012 18:02:12 GMT
- request:
    method: get
    uri: http://localhost:3000/products/4.json
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      User-Agent:
      - Ruby
      X-Api-Key:
      - 4d26276a99cf2b1291000001
      X-Api-Timestamp:
      - '1331661732'
      X-Api-Signature:
      - !binary |-
        OTU1OWJlMTYxZGE2ZDllYmEwNjYyOTM5MjIyMjNhZjg=
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Date:
      - Tue, 13 Mar 2012 18:02:12 GMT
      Status:
      - 404 Not Found
      Connection:
      - close
      Content-Type:
      - application/json; charset=utf-8
      X-Ua-Compatible:
      - IE=Edge
      Cache-Control:
      - no-cache
      X-Request-Id:
      - 7e46ac81603a4aa682886851ce54912f
      X-Runtime:
      - '0.015209'
    body:
      encoding: US-ASCII
      string: ! '{"status_code":404,"status_message":"Not Found","message":"Not Found","type":"BSON::InvalidObjectId","application_trace":["app/controllers/products_controller.rb:65:in
        `load_product''"],"framework_trace":["bson (1.6.0) lib/bson/types/object_id.rb:126:in
        `from_string''","mongoid (2.4.6) lib/mongoid/fields/internal/object_id.rb:38:in
        `serialize''","mongoid (2.4.6) lib/mongoid/criterion/optional.rb:97:in `for_ids''","mongoid
        (2.4.6) lib/mongoid/criteria.rb:310:in `search''","mongoid (2.4.6) lib/mongoid/criterion/inclusion.rb:125:in
        `find''","mongoid (2.4.6) lib/mongoid/finders.rb:84:in `find''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:440:in `_run__3244248498767541306__process_action__2837966185696421672__callbacks''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:405:in `__run_callback''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks''","actionpack
        (3.2.2) lib/abstract_controller/callbacks.rb:17:in `process_action''","actionpack
        (3.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action''","actionpack
        (3.2.2) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action''","activesupport
        (3.2.2) lib/active_support/notifications.rb:123:in `block in instrument''","activesupport
        (3.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument''","activesupport
        (3.2.2) lib/active_support/notifications.rb:123:in `instrument''","actionpack
        (3.2.2) lib/action_controller/metal/instrumentation.rb:29:in `process_action''","actionpack
        (3.2.2) lib/action_controller/metal/params_wrapper.rb:205:in `process_action''","actionpack
        (3.2.2) lib/abstract_controller/base.rb:121:in `process''","actionpack (3.2.2)
        lib/abstract_controller/rendering.rb:45:in `process''","actionpack (3.2.2)
        lib/action_controller/metal.rb:203:in `dispatch''","actionpack (3.2.2) lib/action_controller/metal/rack_delegation.rb:14:in
        `dispatch''","actionpack (3.2.2) lib/action_controller/metal.rb:246:in `block
        in action''","actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:67:in
        `call''","actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:67:in
        `dispatch''","actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:30:in
        `call''","journey (1.0.3) lib/journey/router.rb:68:in `block in call''","journey
        (1.0.3) lib/journey/router.rb:56:in `each''","journey (1.0.3) lib/journey/router.rb:56:in
        `call''","actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:594:in
        `call''","mongoid (2.4.6) lib/rack/mongoid/middleware/identity_map.rb:33:in
        `block in call''","mongoid (2.4.6) lib/mongoid.rb:132:in `unit_of_work''","mongoid
        (2.4.6) lib/rack/mongoid/middleware/identity_map.rb:33:in `call''","warden
        (1.1.1) lib/warden/manager.rb:35:in `block in call''","warden (1.1.1) lib/warden/manager.rb:34:in
        `catch''","warden (1.1.1) lib/warden/manager.rb:34:in `call''","/Users/bturner/.rvm/gems/ruby-1.9.3-p125@hippo/bundler/gems/rack-cors-c512151a6650/lib/rack/cors.rb:51:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/best_standards_support.rb:17:in
        `call''","rack (1.4.1) lib/rack/etag.rb:23:in `call''","rack (1.4.1) lib/rack/conditionalget.rb:25:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/head.rb:14:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/params_parser.rb:21:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/flash.rb:242:in
        `call''","rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context''","rack
        (1.4.1) lib/rack/session/abstract/id.rb:200:in `call''","actionpack (3.2.2)
        lib/action_dispatch/middleware/cookies.rb:338:in `call''","actionpack (3.2.2)
        lib/action_dispatch/middleware/callbacks.rb:28:in `block in call''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:405:in `_run__1795460180543158408__call__3653595690874581875__callbacks''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:405:in `__run_callback''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:385:in `_run_call_callbacks''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks''","actionpack
        (3.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call''","actionpack
        (3.2.2) lib/action_dispatch/middleware/reloader.rb:65:in `call''","actionpack
        (3.2.2) lib/action_dispatch/middleware/remote_ip.rb:31:in `call''","actionpack
        (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call''","actionpack
        (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call''","railties
        (3.2.2) lib/rails/rack/logger.rb:26:in `call_app''","railties (3.2.2) lib/rails/rack/logger.rb:16:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in
        `call''","rack (1.4.1) lib/rack/methodoverride.rb:21:in `call''","rack (1.4.1)
        lib/rack/runtime.rb:17:in `call''","activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in
        `call''","rack (1.4.1) lib/rack/lock.rb:15:in `call''","actionpack (3.2.2)
        lib/action_dispatch/middleware/static.rb:61:in `call''","railties (3.2.2)
        lib/rails/engine.rb:479:in `call''","railties (3.2.2) lib/rails/application.rb:220:in
        `call''","railties (3.2.2) lib/rails/railtie/configurable.rb:30:in `method_missing''","unicorn
        (4.2.0) lib/unicorn/http_server.rb:530:in `process_client''","unicorn (4.2.0)
        lib/unicorn/http_server.rb:604:in `worker_loop''","unicorn (4.2.0) lib/unicorn/http_server.rb:487:in
        `spawn_missing_workers''","unicorn (4.2.0) lib/unicorn/http_server.rb:137:in
        `start''","unicorn (4.2.0) bin/unicorn_rails:209:in `<top (required)>''","/Users/bturner/.rvm/gems/ruby-1.9.3-p125@hippo/bin/unicorn_rails:19:in
        `load''","/Users/bturner/.rvm/gems/ruby-1.9.3-p125@hippo/bin/unicorn_rails:19:in
        `<main>''"],"full_trace":["bson (1.6.0) lib/bson/types/object_id.rb:126:in
        `from_string''","mongoid (2.4.6) lib/mongoid/fields/internal/object_id.rb:38:in
        `serialize''","mongoid (2.4.6) lib/mongoid/criterion/optional.rb:97:in `for_ids''","mongoid
        (2.4.6) lib/mongoid/criteria.rb:310:in `search''","mongoid (2.4.6) lib/mongoid/criterion/inclusion.rb:125:in
        `find''","mongoid (2.4.6) lib/mongoid/finders.rb:84:in `find''","app/controllers/products_controller.rb:65:in
        `load_product''","activesupport (3.2.2) lib/active_support/callbacks.rb:440:in
        `_run__3244248498767541306__process_action__2837966185696421672__callbacks''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:405:in `__run_callback''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks''","actionpack
        (3.2.2) lib/abstract_controller/callbacks.rb:17:in `process_action''","actionpack
        (3.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action''","actionpack
        (3.2.2) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action''","activesupport
        (3.2.2) lib/active_support/notifications.rb:123:in `block in instrument''","activesupport
        (3.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument''","activesupport
        (3.2.2) lib/active_support/notifications.rb:123:in `instrument''","actionpack
        (3.2.2) lib/action_controller/metal/instrumentation.rb:29:in `process_action''","actionpack
        (3.2.2) lib/action_controller/metal/params_wrapper.rb:205:in `process_action''","actionpack
        (3.2.2) lib/abstract_controller/base.rb:121:in `process''","actionpack (3.2.2)
        lib/abstract_controller/rendering.rb:45:in `process''","actionpack (3.2.2)
        lib/action_controller/metal.rb:203:in `dispatch''","actionpack (3.2.2) lib/action_controller/metal/rack_delegation.rb:14:in
        `dispatch''","actionpack (3.2.2) lib/action_controller/metal.rb:246:in `block
        in action''","actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:67:in
        `call''","actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:67:in
        `dispatch''","actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:30:in
        `call''","journey (1.0.3) lib/journey/router.rb:68:in `block in call''","journey
        (1.0.3) lib/journey/router.rb:56:in `each''","journey (1.0.3) lib/journey/router.rb:56:in
        `call''","actionpack (3.2.2) lib/action_dispatch/routing/route_set.rb:594:in
        `call''","mongoid (2.4.6) lib/rack/mongoid/middleware/identity_map.rb:33:in
        `block in call''","mongoid (2.4.6) lib/mongoid.rb:132:in `unit_of_work''","mongoid
        (2.4.6) lib/rack/mongoid/middleware/identity_map.rb:33:in `call''","warden
        (1.1.1) lib/warden/manager.rb:35:in `block in call''","warden (1.1.1) lib/warden/manager.rb:34:in
        `catch''","warden (1.1.1) lib/warden/manager.rb:34:in `call''","/Users/bturner/.rvm/gems/ruby-1.9.3-p125@hippo/bundler/gems/rack-cors-c512151a6650/lib/rack/cors.rb:51:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/best_standards_support.rb:17:in
        `call''","rack (1.4.1) lib/rack/etag.rb:23:in `call''","rack (1.4.1) lib/rack/conditionalget.rb:25:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/head.rb:14:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/params_parser.rb:21:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/flash.rb:242:in
        `call''","rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context''","rack
        (1.4.1) lib/rack/session/abstract/id.rb:200:in `call''","actionpack (3.2.2)
        lib/action_dispatch/middleware/cookies.rb:338:in `call''","actionpack (3.2.2)
        lib/action_dispatch/middleware/callbacks.rb:28:in `block in call''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:405:in `_run__1795460180543158408__call__3653595690874581875__callbacks''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:405:in `__run_callback''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:385:in `_run_call_callbacks''","activesupport
        (3.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks''","actionpack
        (3.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call''","actionpack
        (3.2.2) lib/action_dispatch/middleware/reloader.rb:65:in `call''","actionpack
        (3.2.2) lib/action_dispatch/middleware/remote_ip.rb:31:in `call''","actionpack
        (3.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call''","actionpack
        (3.2.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call''","railties
        (3.2.2) lib/rails/rack/logger.rb:26:in `call_app''","railties (3.2.2) lib/rails/rack/logger.rb:16:in
        `call''","actionpack (3.2.2) lib/action_dispatch/middleware/request_id.rb:22:in
        `call''","rack (1.4.1) lib/rack/methodoverride.rb:21:in `call''","rack (1.4.1)
        lib/rack/runtime.rb:17:in `call''","activesupport (3.2.2) lib/active_support/cache/strategy/local_cache.rb:72:in
        `call''","rack (1.4.1) lib/rack/lock.rb:15:in `call''","actionpack (3.2.2)
        lib/action_dispatch/middleware/static.rb:61:in `call''","railties (3.2.2)
        lib/rails/engine.rb:479:in `call''","railties (3.2.2) lib/rails/application.rb:220:in
        `call''","railties (3.2.2) lib/rails/railtie/configurable.rb:30:in `method_missing''","unicorn
        (4.2.0) lib/unicorn/http_server.rb:530:in `process_client''","unicorn (4.2.0)
        lib/unicorn/http_server.rb:604:in `worker_loop''","unicorn (4.2.0) lib/unicorn/http_server.rb:487:in
        `spawn_missing_workers''","unicorn (4.2.0) lib/unicorn/http_server.rb:137:in
        `start''","unicorn (4.2.0) bin/unicorn_rails:209:in `<top (required)>''","/Users/bturner/.rvm/gems/ruby-1.9.3-p125@hippo/bin/unicorn_rails:19:in
        `load''","/Users/bturner/.rvm/gems/ruby-1.9.3-p125@hippo/bin/unicorn_rails:19:in
        `<main>''"]}'
    http_version: 
  recorded_at: Tue, 13 Mar 2012 18:02:12 GMT
recorded_with: VCR 2.0.0
